### PR TITLE
test(typeconversion): add unit tests for type conversion

### LINKED ISSUE #115: define JS -> Java type conversion rules
When passing a JS value into a Java method on the backend via Vaadin Connect I want to know exactly the value / type coercion rules applied by the Vaadin Connect so that I can build a robust app and know its behavior in all corner cases.

DoD:
 - there is a docs page describing the default JS -> Java value / type coercion rules
 - there are unit tests covering all rules (both FE and BE)
 - the types in scope:
   - all primitives (e.g. `int`)
   - all boxed primitives (e.g. `java.lang.Integer`)
   - `java.lang.String`
   - date / time types
   - JSON objects
   - arrays
   - collections
   - enums
   - maps with string / enum keys
   - beans
 - same tests and docs for the Java -> JS conversion
 - create a list of what needs to change so that type conversion rules make most sense (e.g. what to do with Java long -> JS, date / times both ways, etc)

### PR DESCRIPTION
**Pull request by qtdzz**
Fix #115

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-connect/157)

### CODE REVIEW

**Comment by qtdzz** [comment]
This PR skipped `JSON objects` in the list since it's not clear which type I should test

**Comment by SomeoneToIgnore** [comment]
___
*[doc/type-conversion.asciidoc, line 3 at r3](https://reviewable.io/reviews/vaadin/vaadin-connect/157#-LU-gJ4XDKrZVYW59I91:-LU-gJ4XDKrZVYW59I92:bmsuzgl) ([raw file](https://github.com/vaadin/vaadin-connect/blob/e577c26f265ddb8d2f432301f09e8e2503801089/doc/type-conversion.asciidoc#L3)):*
> ```
> 802
> ```

I know that those order numbers are preliminary currently, but still: 802 is already occupied by `default-client.asciidoc`
Not sure if something's affected by this, so up to you whether to change it or not.

**Comment by SomeoneToIgnore** [comment]
___
*[doc/type-conversion.asciidoc, line 177 at r4](https://reviewable.io/reviews/vaadin/vaadin-connect/157#-LU0CP9K5elg-CG3Q1Jn:-LU0CP9K5elg-CG3Q1Jo:b-ughs67) ([raw file](https://github.com/vaadin/vaadin-connect/blob/bb8693764d39df99879e7320b1b5d580fab4c580/doc/type-conversion.asciidoc#L177)):*
> ```AsciiDoc
> ** An array of items with expected type in Java (or types which can be converted to expected types), for example, if you expected in Java:
> *** `Collection<Integer>`: `[1, 2, 3]` => `[1,2,3]`, `["1","2","3"]` => `[1,2,3]`
> *** `Collection<String>`: `["foo","bar"]` => `["foo","bar"]`
> ```

An interesting case to describe would be `["foo", "bar", "foo"] => Set<String>`

**Comment by SomeoneToIgnore** [comment]
___
*[vaadin-connect/src/test/java/com/vaadin/connect/typeconversion/BaseTypeConversion.java, line 60 at r4](https://reviewable.io/reviews/vaadin/vaadin-connect/157#-LU0KSrm8NoH_bg9_OrI:-LU0Mtnv0nJudYdEbj9C:b-kjutco) ([raw file](https://github.com/vaadin/vaadin-connect/blob/bb8693764d39df99879e7320b1b5d580fab4c580/vaadin-connect/src/test/java/com/vaadin/connect/typeconversion/BaseTypeConversion.java#L60)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Not sure why do you need to specify the response code in your tests, it's always the same — 400.
We might as well check it in this method plus add the response message check (since we might get an incorrect 400 response)
</blockquote></details>

Come to think of it in general, you can rework the whole class API so that there are only two methods to call: one that sends a request and asserts that it fails and one that sends a request and asserts that it passes and has the same expected values.

With this approach you will be able to remove lots of repetition from your tests.

**Comment by SomeoneToIgnore** [comment]
___
*[vaadin-connect/src/test/java/com/vaadin/connect/typeconversion/BaseTypeConversion.java, line 67 at r4](https://reviewable.io/reviews/vaadin/vaadin-connect/157#-LU0OOqdA_ef3ahV9Xi1:-LU0OOqdA_ef3ahV9Xi2:bj983qt) ([raw file](https://github.com/vaadin/vaadin-connect/blob/bb8693764d39df99879e7320b1b5d580fab4c580/vaadin-connect/src/test/java/com/vaadin/connect/typeconversion/BaseTypeConversion.java#L67)):*
> ```Java
> 
>   protected ObjectNode readJson(String s) throws IOException {
>     return objectMapper.readValue(s, ObjectNode.class);
> ```

I feel like something fishy is going on here, but I cannot formulate it properly, so I will just share my thoughts:

I supposed that there is only one ObjectMapper used in the whole project: the one defined in VaadinConnectEndpoint.
The code here looks like if there's one mapper for request parsing and another for our needs.
This feels incorrect, since we might get a situation when mappers behave differently. Also this looks like if we test this test mapper, which might be not good also.

What do you think about the situation?

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-connect/157#-LU09Hw415K2BJ4b8JoT:-LUF6LxD22mjrqY2ze5r:bnkks88) (no related file):*
<details><summary><i>Previously, qtdzz (Tien Nguyen) wrote…</i></summary><blockquote>

@someonetoignore Code is ready
</blockquote></details>

The docs are very good at describing what happens with json -> java conversion, but what about the reverse process?
At least a very special case with big  Java 'long' values is not covered, isn't it?

---

**Pull request merged**
